blank_issues_enabled: false
contact_links:
  - name: Marketplace Q&A
    url: "https://marketplace.visualstudio.com/items?itemName=gritfytechnologies.bicep-cost-lens&ssr=false#qna"
    about: Ask usage questions on the Visual Studio Marketplace Q&A tab.
